version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_cookbook
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./dockerfile
    ports:
      - 5002:5002

  ui:
    image: ui
    depends_on:
      - api
    build:
      context: UI
      dockerfile: ./dockerfile
    ports:
      - 5173:5173

volumes:
  mongo_volume: